// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"ddd/internal/shared/event"
	"ddd/internal/shared/infrastructure"
	"ddd/internal/shopping_cart/application/checkout"
	"ddd/internal/shopping_cart/application/open_save"
	"ddd/internal/shopping_cart/application/send"
	"ddd/internal/shopping_cart/domain"
	infrastructure2 "ddd/internal/shopping_cart/infrastructure"
	"ddd/internal/shopping_cart/web"
	"github.com/gin-gonic/gin"
	"net/http"
)

// Injectors from server.go:

func buildWebServer(context2 context.Context) (WebServer, error) {
	database, err := infrastructure.NewGormDatabase()
	if err != nil {
		return WebServer{}, err
	}
	shoppingCartReadRepo := infrastructure2.NewShoppingCartReadRepo(database)
	eventBus := event.NewEventBus()
	shoppingCartWriteRepo := infrastructure2.NewShoppingCartWriteRepo(database, eventBus)
	shoppingCarts := domain.NewShoppingCarts(shoppingCartReadRepo, shoppingCartWriteRepo, eventBus)
	openAndSave := open_save.NewOpenAndSave(shoppingCarts)
	sendingShoppingCart := send.NewSendingShoppingCart(shoppingCarts, eventBus)
	checkoutShoppingCart := checkout.NewCheckoutShoppingCart()
	shoppingCartsWebHandlers := web.NewShopingCartsWebHanders(openAndSave, sendingShoppingCart, checkoutShoppingCart, shoppingCarts)
	webServer := WebServer{
		shoppingCartWebHandlers: shoppingCartsWebHandlers,
	}
	return webServer, nil
}

// server.go:

type WebServer struct {
	engine                  *gin.Engine
	shoppingCartWebHandlers web.ShoppingCartsWebHandlers
}

func (server *WebServer) Run(port string) {
	server.engine = gin.Default()
	server.engine.GET("/", func(ctx *gin.Context) {
		ctx.String(http.StatusOK, "hello")
	})
	api := server.engine.Group("api")
	server.setupShoppingCartRoutes(api)
	server.engine.Run(port)
}

func (server *WebServer) setupShoppingCartRoutes(api *gin.RouterGroup) {
	v1 := api.Group("/v1")
	v1.POST("/shoppingcart", server.shoppingCartWebHandlers.Open)
	v1.PUT("/shoppingcart", server.shoppingCartWebHandlers.Save)
	v1.POST("/shoppingcart/send", server.shoppingCartWebHandlers.Send)
	v1.POST("/shoppingcart/checkout", server.shoppingCartWebHandlers.Checkout)
}
